CREATE TABLE USER_TB (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR(200) NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	LASTNAME VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	STATUS INT DEFAULT(2),
	PASSWORD VARCHAR(200) NOT NULL
);